// <auto-generated />
using EmployeeManagement.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260303045824_Dtabase creating")]
    partial class Dtabasecreating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nilesh",
                            Salary = 50000
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rahul",
                            Salary = 60000
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Models.Pf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<int>("PfAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpId")
                        .IsUnique();

                    b.ToTable("Pfs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpId = 1,
                            PfAmount = 5000
                        },
                        new
                        {
                            Id = 2,
                            EmpId = 2,
                            PfAmount = 6000
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Models.Pf", b =>
                {
                    b.HasOne("EmployeeManagement.Models.Employee", "Employee")
                        .WithOne("Pf")
                        .HasForeignKey("EmployeeManagement.Models.Pf", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Navigation("Pf")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
