// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Data;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Name = "Alice",
                            PasswordHash = "hashedpassword1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Name = "Bob",
                            PasswordHash = "hashedpassword2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            Name = "Charlie",
                            PasswordHash = "hashedpassword3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "david@example.com",
                            Name = "David",
                            PasswordHash = "hashedpassword4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "eve@example.com",
                            Name = "Eve",
                            PasswordHash = "hashedpassword5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "frank@example.com",
                            Name = "Frank",
                            PasswordHash = "hashedpassword6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "grace@example.com",
                            Name = "Grace",
                            PasswordHash = "hashedpassword7"
                        },
                        new
                        {
                            Id = 8,
                            Email = "hank@example.com",
                            Name = "Hank",
                            PasswordHash = "hashedpassword8"
                        },
                        new
                        {
                            Id = 9,
                            Email = "ivy@example.com",
                            Name = "Ivy",
                            PasswordHash = "hashedpassword9"
                        },
                        new
                        {
                            Id = 10,
                            Email = "jack@example.com",
                            Name = "Jack",
                            PasswordHash = "hashedpassword10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
