-- ALTER TABLE ZIPCODE_INFO
-- ADD CONSTRAINT ZIP_PK PRIMARY KEY (ZIP_CODE);

-- ALTER TABLE ZIPCODE_INFO
-- ADD CONSTRAINT ZIP_CITY_NN CHECK (CITY IS NOT NULL);

-- ALTER TABLE ZIPCODE_INFO
-- ADD CONSTRAINT ZIP_STATE_NN CHECK (STATE IS NOT NULL);

-- ALTER TABLE INSTRUCTOR_INFO
-- ALTER COLUMN INSTRUCTOR_ID NUMERIC NOT NULL;
-- ALTER TABLE INSTRUCTOR_INFO
-- ADD CONSTRAINT INSTRUCTOR_ID_PK PRIMARY KEY (INSTRUCTOR_ID);

-- ALTER TABLE INSTRUCTOR_INFO
-- ADD CONSTRAINT INSTRUCTOR_FN_NN CHECK (INSTRUCTOR_FIRST_NAME IS NOT NULL);

-- ALTER TABLE INSTRUCTOR_INFO
-- ADD CONSTRAINT INSTRUCTOR_LN_NN CHECK (INSTRUCTOR_LAST_NAME IS NOT NULL);


-- ALTER TABLE INSTRUCTOR_INFO
-- ADD CONSTRAINT ZIP_INSTRUCTOR_FK
-- FOREIGN KEY (ZIP_CODE)
-- REFERENCES ZIPCODE_INFO (ZIP_CODE);

-- ALTER TABLE COURSE_INFO
-- ALTER COLUMN COURSE_NO NUMERIC NOT NULL;
-- ALTER TABLE COURSE_INFO
-- ADD CONSTRAINT COURSE_NO_PK PRIMARY KEY (COURSE_NO);

-- ALTER TABLE COURSE_INFO
-- ADD CONSTRAINT COURSE_NAME_NN CHECK (COURSE_NAME IS NOT NULL);

-- ALTER TABLE COURSE_INFO
-- ADD CONSTRAINT COST_NN CHECK (COST IS NOT NULL);

-- ALTER TABLE STUDENT_INFO
-- ALTER COLUMN STUDENT_ID NUMERIC NOT NULL;
-- ALTER TABLE STUDENT_INFO
-- ADD CONSTRAINT STUDENT_ID_PK PRIMARY KEY (STUDENT_ID);

-- ALTER TABLE STUDENT_INFO
-- ADD CONSTRAINT STUDENT_FN_NN CHECK (STUDENT_FIRST_NAME IS NOT NULL);

-- ALTER TABLE STUDENT_INFO
-- ADD CONSTRAINT STUDENT_LN_NN CHECK (STUDENT_LAST_NAME IS NOT NULL);

-- ALTER TABLE STUDENT_INFO
-- ADD CONSTRAINT ZIP_STUDENT_FK
-- FOREIGN KEY (ZIP_CODE)
-- REFERENCES ZIPCODE_INFO(ZIP_CODE);

-- ALTER TABLE SECTION_INFO
-- ALTER COLUMN SECTION_ID NUMERIC NOT NULL;
-- ALTER TABLE SECTION_INFO
-- ADD CONSTRAINT SECTION_ID_PK PRIMARY KEY (SECTION_ID);

ALTER TABLE SECTION_INFO
ADD CONSTRAINT COURSE_SECTION_FK
FOREIGN KEY (COURSE_NO)
REFERENCES COURSE_INFO (COURSE_NO);



