// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_Management_System.Context;

#nullable disable

namespace Student_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312042459_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Student_Management_System.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = ".NET Full Stack Development",
                            DepartmentId = 1,
                            Duration = "6 Months"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Angular Development",
                            DepartmentId = 1,
                            Duration = "4 Months"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Cloud Computing",
                            DepartmentId = 2,
                            Duration = "6 Months"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Cyber Security",
                            DepartmentId = 2,
                            Duration = "5 Months"
                        },
                        new
                        {
                            CourseId = 5,
                            CourseName = "Financial Management",
                            DepartmentId = 3,
                            Duration = "3 Months"
                        });
                });

            modelBuilder.Entity("Student_Management_System.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Computer Science",
                            Location = "Building A"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Information Technology",
                            Location = "Building B"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Business Administration",
                            Location = "Building C"
                        });
                });

            modelBuilder.Entity("Student_Management_System.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Age = 22,
                            CourseId = 1,
                            DepartmentId = 1,
                            Email = "ravi@gmail.com",
                            Gender = "Male",
                            Name = "Ravi Kumar"
                        },
                        new
                        {
                            StudentId = 2,
                            Age = 23,
                            CourseId = 3,
                            DepartmentId = 2,
                            Email = "anjali@gmail.com",
                            Gender = "Female",
                            Name = "Anjali Sharma"
                        },
                        new
                        {
                            StudentId = 3,
                            Age = 24,
                            CourseId = 2,
                            DepartmentId = 1,
                            Email = "suresh@gmail.com",
                            Gender = "Male",
                            Name = "Suresh Reddy"
                        },
                        new
                        {
                            StudentId = 4,
                            Age = 21,
                            CourseId = 5,
                            DepartmentId = 3,
                            Email = "priya@gmail.com",
                            Gender = "Female",
                            Name = "Priya Nair"
                        });
                });

            modelBuilder.Entity("Student_Management_System.Models.Course", b =>
                {
                    b.HasOne("Student_Management_System.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Student_Management_System.Models.Student", b =>
                {
                    b.HasOne("Student_Management_System.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("Student_Management_System.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Student_Management_System.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
